### ISSUE TITLE
Dialog can be higher than the browser window

### ISSUE THREAD

**Issue by thamas** [andykirk/CKEditorFootnotes#12]
If you have "too much" and "too long" footnotes and working a on a smaller screen the "Manage footnotes" dialog screen can be too high which meas that the bottom of the dialog cant be seen, cant be accessed so one can't close the dialog, can't add new footnote, can't resize the window: can't use the tool at all. :(
![screenshot-2015-03-23 12-58-15](https://cloud.githubusercontent.com/assets/1244043/6779454/6891815c-d15c-11e4-8b4a-b2614b37df7c.png)

**Comment by andykirk** [comment]
hi,
Sorry about this. I thought I'd resolved this a while back. Can you let me know your OS and browser and I'll take a look as soon as I can.

Thanks.

**Comment by thamas** [comment]
Hi,
Thanks for the quick reply! I used Firefox and Chrome (latests) on OSX Yosemite.

**Comment by andykirk** [comment]
Hi,
Sorry it took so long to get round to fixing this. I've a few more issues to resolve before I make a release, but you can swap out the dialog file directly if you don't want to wait.

Thanks

**Comment by thamas** [comment]
Hi Andy,

thank you very much for your work providing the results for free!
