### ISSUE TITLE
Cannot create footnotes if track changes plugin is enabled

### ISSUE THREAD

**Issue by tuhlmann** [andykirk/CKEditorFootnotes#14]
In our ckeditor instance we use the track changes plugin (http://ckeditor.com/addon/lite) and are testing out the footnotes plugin.

It works fine if the track changes plugin is disabled. However when it is enabled, the following error is thrown inside the footnotes plugin:

```
Uncaught TypeError: Cannot read property 'initEditable' of undefined
CKEDITOR.plugins.add.reorderMarkers @ plugin.js?t=F0RD:292
CKEDITOR.plugins.add.build @ plugin.js?t=F0RD:147
onOk @ footnotes.js?t=F0RD:149
(anonymous function) @ ckeditor.js:526
j @ ckeditor.js:10
CKEDITOR.event.CKEDITOR.event.fire @ ckeditor.js:12
CKEDITOR.tools.extend.okButton.CKEDITOR.tools.extend.onClick @ ckeditor.js:548
(anonymous function) @ ckeditor.js:491
j @ ckeditor.js:10
CKEDITOR.event.CKEDITOR.event.fire @ ckeditor.js:12
CKEDITOR.ui.dialog.button.CKEDITOR.tools.extend.click @ ckeditor.js:490
(anonymous function) @ ckeditor.js:482
j @ ckeditor.js:10CKEDITOR.event.CKEDITOR.event.fire @ ckeditor.js:12
CKEDITOR.dom.domObject.a @ ckeditor.js:45
```

Is that a known problem? Should I investigate on the footnote or track changes side of things?

Any pointers for a possible fix would be greatly appreciated.

We use the following versions:

ckeditor: 4.4.7
track changes plugin: 1.2.13
footnotes plugin: 1.0.8 

Thanks,
Torsten.

**Comment by andykirk** [comment]
Hi Torsten

I've not used the track changes plugin so I've not encountered this problem before (and it hasn't been reported before).
Sounds like it might be an event-timing issue. I design the footnotes plugin to work with whatever markup is in place in the editor - but obviously something isn't playing nice.
I may be that I need to make sure the Footnotes events are fire last or something

If you could raise an issue on GitHub (https://github.com/andykirk/CKEditorFootnotes) I'll investigate as soon as I can (some time in the next few weeks - when time allows).
There are a bunch of other issue I intend to look at too, so I plan to tackle them at the same time.

Please let me know if you make any further discoveries. Sorry I can't be any more immediate help.

Andy

________________________________

**Comment by tuhlmann** [comment]
Hi Andy, thanks for the quick response.
Is there some other place to add this issue to, as I already opened a Github ticket (https://github.com/andykirk/CKEditorFootnotes/issues/14)

Thanks,
Torsten.

**Comment by andykirk** [comment]
Ok, thanks.

Sorry - I didn't notice the issue come up for some reason. That's great.

Andy
________________________________

**Comment by tuhlmann** [comment]
I have prepared an example that demonstrates the problem: http://tuhlmann.github.io/ckeditor-footnotes/

To replicate the problem:

* Open tuhlmann.github.io/ckeditor-footnotes
* The track changes plugin should be enabled
* click on the footnotes button, add some text in the appearing dialog
* click OK in the dialog
* ==> The dialog does not disappear and an error is logged in the developer console.

Thanks for your help,
Torsten.

**Comment by tuhlmann** [comment]
The track changes people provided a fix for this, one part is a pull request against the footnotes plugin, another part is a change in their plugin: https://github.com/loopindex/ckeditor-track-changes/issues/47

Integrating both changes I can confirm it works.

**Comment by andykirk** [comment]
Hi,
I've implemented the fix.
I'm going through some other issue before I make a release, but you can use the master files directly if you need to.

Thanks again for reporting.

**Comment by tuhlmann** [comment]
Thanks!
I did integrate pull request #15 locally and that is working fine. I will update to your version.
