### ISSUE TITLE
Paste from Word Compatibility

### ISSUE THREAD

**Issue by mooreacreations** [andykirk/CKEditorFootnotes#20]
It looks like there is no compatibility with footnotes pasted from Word. They are not recognized as footnotes by the plugin.

**Comment by andykirk** [comment]
Hi,
Sorry for the delay in replying. I've already written this as a separate plugin for a paying client - I'm just waiting to here back from him he's OK if I release this plugin alongside this one. I don't envisage a problem as there was no agreement in place, but I thought it polite to check,

Thanks for your patience.

Andy

**Comment by andykirk** [comment]
Hi,
Sorry for the delay. I'm happy to confirm I'm able to release the PasteFromWord / Footnotes plugin.

Now I just have to decide whether it's best to put it in its own repo or bundle it in with this one.

**Comment by mooreacreations** [comment]
Hi Andy,

Thanks for the reply and thank you for your work ! It may be interesting to keep only one plugin as it's all part of the same functionality.
Please let me know when the plugin is released :)

**Comment by andykirk** [comment]
Hi,

https://github.com/andykirk/CKEditorFootnotes-PasteFromWord

I've decided to keep it in a separate repo (as it actually is a separate plugin), so it can receive it's own issues etc.

I'll add it to the CKEditor Plugin site when I can.
