### ISSUE TITLE
Update text of footonote

### ISSUE THREAD

**Issue by alessandrots** [andykirk/CKEditorFootnotes#30]
Actually, what I have here is a question.

I'm sorry, maybe this is not even the right place.

I've seen all the code in this plugin. My question is about update a marker.

When the user clicks the footnote href number and opens the dialog, the text that the user places there will change exactly a specific endnote.
I have seen that a new ID is generated and the addFootnote function adds a new html li.

My initial scenario:
I added 3 footnote.

```
<section class="footnotes">
 ...
    <ol>
        <li data-footnote-id="yo7kq" id="footnote-1"><sup><a href="#footnote-marker-1-1">^</a> </sup><cite>1</cite></li>
        <li data-footnote-id="7p8e2" id="footnote-2"><sup><a href="#footnote-marker-2-1">^</a> </sup><cite>2</cite></li>
        <li data-footnote-id="tjbp6" id="footnote-3"><sup><a href="#footnote-marker-3-1">^</a> </sup><cite>3</cite></li>
    </ol>
</section>
```

Then I clicked on the second marker, opened the dialog and changed the text.

In the reorderMarkers function a new ID is added this.footnote_ids = 
["yo7kq", "7p8e2", "tjbp6", "sqs80"]
what I understand is that the li tag is updated, it overwritten. Is that correct?

```
<section class="footnotes">
...
<ol>
    <li data-footnote-id="yo7kq" id="footnote-1"><sup><a href="#footnote-marker-1-1">^</a> </sup><cite>1</cite></li>
    <li data-footnote-id="sqs80" id="footnote-2"><sup><a href="#footnote-marker-2-1">^</a> </sup><cite>NEW_2</cite></li>
    <li data-footnote-id="tjbp6" id="footnote-3"><sup><a href="#footnote-marker-3-1">^</a> </sup><cite>3</cite></li>
</ol>
</section>
```

My doubts:     
1) When changing the footnote-2 information how is this replacement made in html? Does the append of a new li exclude the former?

2) Is there any way I can get the text for a footnote, when the user clicks the button on the toolbar the text has already been appeared on textearea of dialog

**Comment by andykirk** [comment]
Hi,
I'm afraid I really don't understand what you're asking.

The [AB2] toolbar button is used for inserting new or existing footnotes, not editing them.
The content of a footnote can be edited directly in the edit area (footnotes section).

Whilst editing, the markers in the content e.g. [1] shouldn't activate a dialog or anything - they're widgets so you can move them around.
Similarly, the markers (^, a, b, etc) in the footnotes sections shouldn't activate anything whilst in the editor.

If that doesn't answer your question, please can you have another go at asking it, perhaps with screenshots or something?

Thanks.

**Comment by alessandrots** [comment]
Andy,

In fact, your answer answered my question "The content of a footnote can be edited directly in the edit area (footnotes section)".

Thank you very much for your attention and quick response.

By the way, this plugin is very good and is helping me a lot.

Regards,

Alessandro
