### ISSUE TITLE
Plan for CKEditor5?

### ISSUE THREAD

**Issue by lal65** [andykirk/CKEditorFootnotes#46]
CKEditor4 will be losing security coverage next year.  Is there any plan to refactor things to work with CKEditor5 in the coming year?

The changes between 4 and 5 are pretty dramatic.  It'd likely mean completely rewriting this project.  If the plan is that CKEditor5 will not be supported, that's fine, but let's document it :).

Let's discuss, thanks!

**Comment by andykirk** [comment]
Thanks for the input.
I don't currently have the time to re-write this plugin for CKEditor5, unfortunately.
I'd never say never but it's not on the horizon. If someone else took this on I'd gladly link to it or host it here.

Thanks,
Andy
